# About

This is material for our short courses on forecasting univariate fisheries data.  Please see the NWFSC Time Series Analysis [website](https://nwfsc-timeseries.github.io/)  for other courses, R packages and papers on multivariate time series analysis (PIs: Eli Holmes, Mark Scheurell, Eric Ward).

*Contact*:

Eli Holmes, PhD
Northwest Fisheries Science Center
National Marine Fisheries Service
2725 Montlake Blvd East
Seattle, WA USA
eli.holmes@noaa.gov
www.faculty.washington.edu/eeholmes

# Resources

Rob Hyndman book on forecasting and the **forecast** package: [Forecasting Principals and Practice](https://otexts.org/fpp2/)

NWFSC Time Series Analysis products: https://nwfsc-timeseries.github.io/  (PIs: Eli Holmes, Mark Scheurell, Eric Ward)

* Courses on multivariate and univariate time series analysis applied to messy fisheries and ecological data.

* R packages for fitting time series models.  Bayesian and maximum-likelihood.

* online books:

  - [Applied Time-Series Analysis for Fisheries and Environmental Data](https://nwfsc-timeseries.github.io/atsa-labs/)
  
  - [Fisheries Catch Forecasting](https://fish-forecast.github.io/Fish-Forecast-Bookdown/)



