---
title: "ARMA Models"
---

*For labs*: Click the 'Rmd file' link and download to your lab folder.  Open RStudio.  Switch to your lab project, by clicking button in top right (click create a new project if you did not do this step before).  The `greeklandings` and `chinook` datasets are in the **FishForecast** package. Install that package if you have not already:

```
library(devtools)
devtools::install_github("Fish-Forecast/FishForecast")
```

- Lecture 1 [Introduction to ARMA Models](Forecasting_3-1_-_ARMA_Intro.html)

- Lab 1 Intro to ARMA models and diagnostic plots: [ARMA Lab 1](ARMA Lab 1.html) - [Rmd file](Labs/ARMA Lab 1.Rmd)

- Lecture 2 [Stationarity](Forecasting_3-2_-_ARMA_Stationarity.html)

- Lab 2 Test the Greek catch data for stationarity [ARMA Lab 2 Stationarity](ARMA Lab 2 Stationarity.html) - [Rmd file](Labs/ARMA Lab 2 Stationarity.Rmd)

- Lecture 3 [Selecting Model Structure](Forecasting_3-3_-_ARMA_Model_Structure.html)

- Lecture 4 [Fitting ARMA Models](Forecasting_3-4_-_ARMA_Fitting_Models.html)

- Lab 3 Fit ARMA Models to the Greek catch data  [ARMA Lab 3 Fitting](ARMA Lab 3 Fitting.html) - [Rmd file](Labs/ARMA Lab 3 Fitting.Rmd) - [R Code from Lecture 4](Labs/R_scripts/Forecasting 3-4 - ARMA Fitting Models.R)

- Lecture 5 [Forecasting from ARMA Models](Forecasting_3-5_-_ARMA_Forecasting.html)

- Lab 4 Create your own forecasts [R Code from Lecture 5](Labs/R_scripts/Forecasting 3-5 - ARMA Forecasting.R)

- Lecture 6 [Cross Validation](Forecasting_3-6_-_ARMA_Performance.html)

- Lab 5 Test your forecasts [R Code from Lecture 6](Labs/R_scripts/Forecasting 3-6 - ARMA Performance.R)

- Lecture 7 [Seasonal ARMA Models](Forecasting_3-7_-_ARMA_Seasonal_Models.html)

- Lab 6 Seasonal models [R Code from Lecture 6](Labs/R_scripts/Forecasting 3-7 - ARMA Seasonal Models.R)



