---
title: "Exponential Smoothing Models"
---

*For labs*: Click the 'Rmd file' link and download to your lab folder.  Open RStudio.  Switch to your lab project, by clicking button in top right (click create a new project if you did not do this step before).  The `greeklandings` and `chinook` datasets are in the **FishForecast** package. Install that package if you have not already:

```
library(devtools)
devtools::install_github("Fish-Forecast/FishForecast")
```

- Lecture 1 [Exponential Smoothing Models](Forecasting_4-1_-_Exp_Smoothing.html)

- Lab 1 Create forecasts with exponential smoothing models - [R Code from Lecture 1](Labs/R_scripts/Forecasting 4-1 - Exp Smoothing.R)

- Lab 2 Compare a set of models [ETS Lab 1 Evaluation](ETS Lab 1 Evaluation.html) - [Rmd file](Labs/ETS Lab 1 Evaluation.Rmd)

- Lecture 2 [Seasonality with exponential smoothing and ARIMA models](Forecasting_4-2_-_ETS_Seasonality.html)

- Lab 3 Seasonal models - [R Code from Lecture 2](Labs/R_scripts/Forecasting 4-2 - ETS Seasonality.R) - [chinook data](https://fish-forecast.github.io/Catch-Forecasting-INCOIS/chinook.RData)

Reference.  Rob J Hyndman (lead on the forecast package)  and George Athanasopoulos have an excellent online text on practical forecasting and exponential smoothing. Read [their chapter](https://otexts.org/fpp2/expsmooth.html) on exponential smoothing to learn more about these models and how to use them.


